docs: replace usage of default role with emphasis.
With the transition from sphinx 8.2.3 to 9.1.0 we started to see:
sphinx.errors.SphinxError: cannot determine default role!
With 8.2.3 the usages of the default role led to <cite> elements in html.
We now use inline markup for emphasis instead of relying on the default role.
This results in <em> elements instead of <cite> elements, which seems more
in accordance with our usage.